server:
  port: ":8080"

database:
  host: postgres
  port: "5432"
  user: postgres
  password: password
  name: flight_service_db

redis:
  host: redis
  port: "6379"
  password: ""
  db: 0

kafka:
  brokers:
    - "kafka:9092"
  topic: "flight-events"
  group_id: "flight-service-group"
  producer:
    required_acks: "WaitForAll"
    retry_max: 3
  consumer:
    initial_offset: "Oldest"
    retry_attempts: 3
    retry_delay: "5s"